# Generated by Django 4.1.2 on 2023-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="card_heading",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
