# Generated by Django 4.1.2 on 2023-08-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_cards_card_details_alter_cards_card_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="cards", name="card_details",),
    ]
