# Generated by Django 4.1.2 on 2023-08-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_cards_card_details_alter_cards_card_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cards",
            name="card_details",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
