# Generated by Django 4.1.2 on 2023-08-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_cards_card_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("app_for", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
