# Generated by Django 4.1.2 on 2023-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_appointments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
