# Generated by Django 4.1.2 on 2023-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="usern",
            field=models.CharField(default=None, max_length=254, null=True),
        ),
    ]
