# Generated by Django 4.1.2 on 2023-09-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_blog"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="uname",),
    ]
